# Generated by Django 3.0.4 on 2020-04-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
        ),
        migrations.RemoveField(
            model_name='roomcategory',
            name='hotel',
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel'),
            preserve_default=False,
        ),
    ]
